create table customer_details (
                                  id long generated by default as identity,
                                  password varchar(100),
                                  user_name varchar(100),
                                  is_expired boolean,
                                  is_locked boolean,
                                  is_credentials boolean,
                                  is_active boolean,
                                  roles varchar(100),
                                  primary key (id)
);

create table customer_date (
                               id long generated by default as identity,
                               customer_name varchar(30),
                               cusomer_details_id bigint,
                               PRIMARY KEY (id)
);

create table car_table (
                           id long generated by default as identity,
                           car_name varchar(50),
                           car_brand varchar(50),
                           make_year date,
                           km int,
                           customer_entity_id bigint,
                           primary key (id)
);



