CREATE TABLE IF NOT EXISTS public.customer_date
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customer_authorities character varying(255) COLLATE pg_catalog."default",
    customer_name character varying(255) COLLATE pg_catalog."default",
    customer_role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customer_date_pkey PRIMARY KEY (id)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.customer_date
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.car_table
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    car_brand character varying(255) COLLATE pg_catalog."default",
    car_name character varying(255) COLLATE pg_catalog."default",
    km integer NOT NULL,
    make_year date,
    customer_entity_id bigint,
    CONSTRAINT car_table_pkey PRIMARY KEY (id),
    CONSTRAINT fk7qjsbd9ll4akqm2skfb7jvvr7 FOREIGN KEY (customer_entity_id)
    REFERENCES public.customer_date (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.car_table
    OWNER to postgres;