CREATE TABLE IF NOT EXISTS public.car_table
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    car_brand character varying(255) COLLATE pg_catalog."default",
    car_name character varying(255) COLLATE pg_catalog."default",
    km integer NOT NULL,
    make_year date,
    customer_entity_id bigint,
    CONSTRAINT car_table_pkey PRIMARY KEY (id),
    CONSTRAINT fk7qjsbd9ll4akqm2skfb7jvvr7 FOREIGN KEY (customer_entity_id)
        REFERENCES public.customer_date (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.car_table
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.customer_date
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customer_name character varying(255) COLLATE pg_catalog."default",
    cusomer_details_id bigint,
    CONSTRAINT customer_date_pkey PRIMARY KEY (id),
    CONSTRAINT fkl9r7vj45g2ve3cof8ylcthreo FOREIGN KEY (cusomer_details_id)
        REFERENCES public.customer_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.customer_date
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.customer_details
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_active boolean NOT NULL,
    is_credentials boolean NOT NULL,
    is_expired boolean NOT NULL,
    is_locked boolean NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    roles character varying(255) COLLATE pg_catalog."default",
    user_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customer_details_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.customer_details
    OWNER to postgres;